name: Build

on: [push]

env:
  DATABASE_URL: http://localhost
  NEXTAUTH_URL: http://localhost
  NEXTAUTH_SECRET: secret
  GITHUB_ID: 123
  GITHUB_SECRET: secret
  NEXT_PUBLIC_APP_URL: http://localhost

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node_version: [20.9.0]
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8.11.0

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm build
